### ISSUE TITLE
Vertical Continuous Scroll?

### ISSUE THREAD

**Issue by Darshan10298** [scoute-dich/MuPDF#3]
The Material effect is Nice...!
but can you plzz change the Scrolling to Vertical with continuous scroll just like Google Pdf viewer or Ebookdroid?
That would be a Nice feature..

**Comment by scoute-dich** [comment]
I don't think that I can implement this. I don't understand much from developing. I just themed the design, since I don't like the ui of the original application.

But when I have time I'll take a look in the code.

**Comment by Darshan10298** [comment]
ok.. :)
will be waiting :D
